### ISSUE TITLE
Scripts not working in Coop/Multiplayer (LZDoom)

### ISSUE THREAD

**Issue by nimlouth** [mmaulwurff/weapons-menu#14]
When trying to use the menu during a coop/multiplayer match, a "Player X tried to puke script X" message appears. The menu doesn't work in consecuence.

**Comment by mmaulwurff** [comment]
Thanks for reporting!

This is kind of a known issue, Weapon Menu was not designed for multiplayer from the start. It cannot be just fixed, the way WM operates is not suitable for multiplayer. I hope that at some point in the future I will rewrite this project, and I will keep multiplayer in mind then.

Edit: also, welcome to GitHub!

**Comment by mmaulwurff** [comment]
Won't do, is fixed in https://github.com/mmaulwurff/gearbox/
